experiments_path: experiments/
device: cpu

dataloader:
  batch_size: 64
  sampler: ImbalancedDatasetSampler

data:
  root_dir: /home/bohdan/CoronaryArteryPlaqueIdentification/data
  filters:
    arteries: [ 'LAD', 'D-1', 'D-2', 'D-3', 'PLV_RCA', 'LCX',  'OM-2', 'RCA', 'PLV_LCX', 'OM-3', 'PDA_LCX','OM-1', 'OM' ]
    viewpoint_index_step: 3
  groups:
    0: [ 'NORMAL','-']
    1: ['<25%', '<35%', '25-50%', '25%', '<50%']
    2: ['50%', '70%','*50%', '50-70%', '70-90%', '90-100%', '>50%', '>70%', '90%', '>90%','75%', '>75%']
  augmentation:
    name: MediumAugFixed
    parameters:
      p: 0.8

model:
  name: ShuffleNetv2
  parameters:
    pretrained: true

optimizer:
  name: Adam
  parameters:
    lr: 0.001

loss:
  name: OHEMLoss
  parameters:
    k: 10