experiments_path: experiments/
device: cuda
random_state: 42

dataloader:
  batch_size: 3
  sampler: BalancedBatchSampler
  accumulation_steps: 3

data:
  root_dir: /home/petryshak/CoronaryArteryPlaqueIdentification/data/all_branches_with_pda_plv
  filters:
    arteries: [ 'LAD', 'D-1', 'D-2', 'D-3', 'PLV_RCA', 'LCX',  'OM-2', 'RCA', 'PLV_LCX', 'OM-3', 'PDA_LCX','OM-1', 'OM' ]
    viewpoint_index_step: 3
  groups:
    0: [ 'NORMAL','-']
    1: ['<25%', '<35%', '25-50%', '25%', '<50%']
    2: ['50%', '70%','*50%', '50-70%', '70-90%', '90-100%', '>50%', '>70%', '90%', '>90%','75%', '>75%']
  augmentation:
    name: SafeAug
    parameters:
      p: 0.8

model:
  name: LSTMClassification
#  parameters:
#    pretrained: true

optimizer:
  name: Adam
  parameters:
    lr: 0.0001

loss:
  name: CrossEntropyLoss
