experiments_path: experiments/

dataloader:
  batch_size: 64
  sampler: ''

data:
  filters:
    arteries: [ 'LAD', 'D-1', 'D-2', 'D-3' ]
    viewpoint_index_step: 3
  groups:
    0: [ 'NORMAL' ]
    1: [ '<25%', '25-50%', '25%' ]
    2: [ '50%', '70%', '50-70%', '70-90%', '90-100%', '>50%' ]
  root_dir: /home/petryshak/CoronaryArteryPlaqueIdentification/data/binary_classification_all_branches/

model:
  name: ResNet18
  parameters:
    pretrained: true

optimizer:
  name: Adam
  parameters:
    lr: 0.001
